from pathlib import Path

p=Path('FactionLedgerIQ.user.js')
s=p.read_text()

s=s.replace('// @version      1.2.4','// @version      1.2.5',1)
s=s.replace("const VERSION='1.2.4';","const VERSION='1.2.5';",1)
s=s.replace("const PRE_RESET_KEY='factionledgeriq_v1_pre_reset';","const PRE_RESET_KEY='factionledgeriq_v1_pre_reset';\nconst RECOVERY_DB='factionledgeriq_v1_recovery';\nconst RECOVERY_STORE='snapshots';",1)

anchor="function toast(msg){let e=document.getElementById('fliq-v1-toast');if(!e){e=document.createElement('div');e.id='fliq-v1-toast';document.body.appendChild(e);}e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2800);}"
addition=anchor+"\n"+r'''function recoveryDb(){return new Promise((resolve,reject)=>{try{const req=indexedDB.open(RECOVERY_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(RECOVERY_STORE))db.createObjectStore(RECOVERY_STORE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Recovery database could not be opened'));}catch(e){reject(e);}});}
async function recoverySet(key,value){const db=await recoveryDb();return new Promise((resolve,reject)=>{const tx=db.transaction(RECOVERY_STORE,'readwrite');tx.objectStore(RECOVERY_STORE).put(value,key);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{const e=tx.error;db.close();reject(e||new Error('Recovery snapshot could not be saved'));};tx.onabort=()=>{const e=tx.error;db.close();reject(e||new Error('Recovery snapshot save was aborted'));};});}
async function recoveryGet(key){const db=await recoveryDb();return new Promise((resolve,reject)=>{const tx=db.transaction(RECOVERY_STORE,'readonly'),req=tx.objectStore(RECOVERY_STORE).get(key);req.onsuccess=()=>{const v=req.result;db.close();resolve(v||null);};req.onerror=()=>{const e=req.error;db.close();reject(e||new Error('Recovery snapshot could not be read'));};});}
async function recoveryDelete(key){const db=await recoveryDb();return new Promise((resolve,reject)=>{const tx=db.transaction(RECOVERY_STORE,'readwrite');tx.objectStore(RECOVERY_STORE).delete(key);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{const e=tx.error;db.close();reject(e||new Error('Recovery snapshot could not be deleted'));};});}
async function migrateLegacyRecoverySnapshots(){for(const [legacyKey,idbKey] of [[PRE_RESET_KEY,'pre_reset'],[PRE_RESTORE_KEY,'pre_restore']]){const raw=localStorage.getItem(legacyKey);if(!raw)continue;try{let parsed;try{parsed=JSON.parse(raw);}catch(e){parsed=raw;}await recoverySet(idbKey,parsed);localStorage.removeItem(legacyKey);}catch(e){console.warn('[FLIQ] recovery snapshot migration failed',legacyKey,e);}}}'''
if anchor not in s: raise SystemExit('toast anchor not found')
s=s.replace(anchor,addition,1)

old=r'''async function restoreBackupFromUi(){const ta=document.getElementById('fliq-backup-import'),file=document.getElementById('fliq-backup-file')&&document.getElementById('fliq-backup-file').files&&document.getElementById('fliq-backup-file').files[0];let text=String(ta&&ta.value||'').trim();if(!text&&file)text=await file.text();if(!text)throw new Error('Choose a backup file or paste backup JSON');let b;try{b=JSON.parse(text);}catch(e){throw new Error('Backup JSON could not be read');}validateBackupEnvelope(b);const previous={kind:'FactionLedgerIQPreRestore',savedAt:new Date().toISOString(),state:clone(state)};localStorage.setItem(PRE_RESTORE_KEY,JSON.stringify(previous));const existingKey=apiKey();state=hydrateState(b.state,existingKey);state.updatedAt=new Date().toISOString();localStorage.setItem(STATE_KEY,JSON.stringify(state));currentAudit=null;restartPolling();render();toast('Backup restored');}
function undoLastRestore(){const raw=localStorage.getItem(PRE_RESTORE_KEY);if(!raw)throw new Error('No pre-restore snapshot is available');let b;try{b=JSON.parse(raw);}catch(e){throw new Error('Recovery snapshot is unreadable');}if(!b||b.kind!=='FactionLedgerIQPreRestore'||!b.state)throw new Error('Recovery snapshot is invalid');const existingKey=apiKey();state=hydrateState(b.state,existingKey);state.updatedAt=new Date().toISOString();localStorage.setItem(STATE_KEY,JSON.stringify(state));localStorage.removeItem(PRE_RESTORE_KEY);currentAudit=null;restartPolling();render();toast('Last restore undone');}'''
new=r'''async function restoreBackupFromUi(){const ta=document.getElementById('fliq-backup-import'),file=document.getElementById('fliq-backup-file')&&document.getElementById('fliq-backup-file').files&&document.getElementById('fliq-backup-file').files[0];let text=String(ta&&ta.value||'').trim();if(!text&&file)text=await file.text();if(!text)throw new Error('Choose a backup file or paste backup JSON');let b;try{b=JSON.parse(text);}catch(e){throw new Error('Backup JSON could not be read');}validateBackupEnvelope(b);const previous={kind:'FactionLedgerIQPreRestore',savedAt:new Date().toISOString(),state:clone(state)};await recoverySet('pre_restore',previous);localStorage.removeItem(PRE_RESTORE_KEY);const existingKey=apiKey();state=hydrateState(b.state,existingKey);state.updatedAt=new Date().toISOString();localStorage.setItem(STATE_KEY,JSON.stringify(state));currentAudit=null;restartPolling();render();toast('Backup restored');}
async function undoLastRestore(){let b=await recoveryGet('pre_restore');if(!b){const raw=localStorage.getItem(PRE_RESTORE_KEY);if(raw){try{b=JSON.parse(raw);}catch(e){throw new Error('Recovery snapshot is unreadable');}}}if(!b)throw new Error('No pre-restore snapshot is available');if(!b||b.kind!=='FactionLedgerIQPreRestore'||!b.state)throw new Error('Recovery snapshot is invalid');const existingKey=apiKey();state=hydrateState(b.state,existingKey);state.updatedAt=new Date().toISOString();localStorage.setItem(STATE_KEY,JSON.stringify(state));await recoveryDelete('pre_restore').catch(()=>{});localStorage.removeItem(PRE_RESTORE_KEY);currentAudit=null;restartPolling();render();toast('Last restore undone');}'''
if old not in s: raise SystemExit('restore block not found')
s=s.replace(old,new,1)

old=r'''function resetLedgerDataFromUi(){const input=document.getElementById('fliq-reset-confirm'),word=String(input&&input.value||'').trim();if(word!=='RESET')throw new Error('Type RESET exactly to reset ledger data');const oldRaw=localStorage.getItem(STATE_KEY)||JSON.stringify(state),keepSettings=clone(state.settings||DEFAULT.settings),keepWhitelist=clone(state.whitelist||[]),now=new Date().toISOString(),fresh=clone(DEFAULT);fresh.settings={...DEFAULT.settings,...keepSettings};fresh.whitelist=keepWhitelist;fresh.createdAt=now;fresh.updatedAt=now;fresh.diagnostics={...DEFAULT.diagnostics,apiStatus:String(keepSettings.apiKey||'').trim()?'Ready to sync':'API key required'};localStorage.removeItem(PRE_RESET_KEY);localStorage.removeItem(STATE_KEY);try{localStorage.setItem(PRE_RESET_KEY,oldRaw);localStorage.setItem(STATE_KEY,JSON.stringify(fresh));}catch(e){localStorage.removeItem(PRE_RESET_KEY);localStorage.removeItem(STATE_KEY);localStorage.setItem(STATE_KEY,oldRaw);throw new Error('Reset could not create a recovery snapshot because device storage is full');}state=fresh;itemCatalog=[];itemCatalogLoadedAt=0;currentAudit=null;activeTab='home';restartPolling();render();toast('Ledger data reset — Undo is available in Settings');}
function undoLastLedgerReset(){const raw=localStorage.getItem(PRE_RESET_KEY);if(!raw)throw new Error('No pre-reset snapshot is available');let b;try{b=JSON.parse(raw);}catch(e){throw new Error('Pre-reset snapshot is unreadable');}const snapshot=b&&b.kind==='FactionLedgerIQPreReset'?b.state:b;if(!snapshot||typeof snapshot!=='object')throw new Error('Pre-reset snapshot is invalid');const existingKey=apiKey(),currentRaw=localStorage.getItem(STATE_KEY)||JSON.stringify(state),restored=hydrateState(snapshot,existingKey);restored.updatedAt=new Date().toISOString();localStorage.removeItem(STATE_KEY);localStorage.removeItem(PRE_RESET_KEY);try{localStorage.setItem(STATE_KEY,JSON.stringify(restored));}catch(e){localStorage.setItem(PRE_RESET_KEY,raw);localStorage.setItem(STATE_KEY,currentRaw);throw new Error('Undo could not restore the ledger because device storage is full');}state=restored;currentAudit=null;restartPolling();render();toast('Last ledger reset undone');}'''
new=r'''async function resetLedgerDataFromUi(){const input=document.getElementById('fliq-reset-confirm'),word=String(input&&input.value||'').trim();if(word!=='RESET')throw new Error('Type RESET exactly to reset ledger data');const previous={kind:'FactionLedgerIQPreReset',savedAt:new Date().toISOString(),state:clone(state)},keepSettings=clone(state.settings||DEFAULT.settings),keepWhitelist=clone(state.whitelist||[]),now=new Date().toISOString(),fresh=clone(DEFAULT);await recoverySet('pre_reset',previous);localStorage.removeItem(PRE_RESET_KEY);fresh.settings={...DEFAULT.settings,...keepSettings};fresh.whitelist=keepWhitelist;fresh.createdAt=now;fresh.updatedAt=now;fresh.diagnostics={...DEFAULT.diagnostics,apiStatus:String(keepSettings.apiKey||'').trim()?'Ready to sync':'API key required'};state=fresh;itemCatalog=[];itemCatalogLoadedAt=0;currentAudit=null;activeTab='home';localStorage.setItem(STATE_KEY,JSON.stringify(state));restartPolling();render();toast('Ledger data reset — Undo is available in Settings');}
async function undoLastLedgerReset(){let b=await recoveryGet('pre_reset');if(!b){const raw=localStorage.getItem(PRE_RESET_KEY);if(raw){try{b=JSON.parse(raw);}catch(e){throw new Error('Pre-reset snapshot is unreadable');}}}if(!b)throw new Error('No pre-reset snapshot is available');const snapshot=b&&b.kind==='FactionLedgerIQPreReset'?b.state:b;if(!snapshot||typeof snapshot!=='object')throw new Error('Pre-reset snapshot is invalid');const existingKey=apiKey(),restored=hydrateState(snapshot,existingKey);restored.updatedAt=new Date().toISOString();localStorage.setItem(STATE_KEY,JSON.stringify(restored));await recoveryDelete('pre_reset').catch(()=>{});localStorage.removeItem(PRE_RESET_KEY);state=restored;currentAudit=null;restartPolling();render();toast('Last ledger reset undone');}'''
if old not in s: raise SystemExit('reset block not found')
s=s.replace(old,new,1)

s=s.replace("if(a==='undo-restore'){try{undoLastRestore();}catch(e){toast(String(e&&e.message||e));}return;}","if(a==='undo-restore'){try{t.disabled=true;await undoLastRestore();}catch(e){toast(String(e&&e.message||e));t.disabled=false;}return;}",1)
s=s.replace("if(a==='reset-ledger'){try{resetLedgerDataFromUi();}catch(e){toast(String(e&&e.message||e));}return;}","if(a==='reset-ledger'){try{t.disabled=true;await resetLedgerDataFromUi();}catch(e){toast(String(e&&e.message||e));t.disabled=false;}return;}",1)
s=s.replace("if(a==='undo-ledger-reset'){try{undoLastLedgerReset();}catch(e){toast(String(e&&e.message||e));}return;}","if(a==='undo-ledger-reset'){try{t.disabled=true;await undoLastLedgerReset();}catch(e){toast(String(e&&e.message||e));t.disabled=false;}return;}",1)

old_boot="function boot(){const cleanedPurchases=purgePreWhitelistPurchases(),cleanedHistory=purgePreTrackingEvents(),cleanedInferred=migrateInferredPersonal();if(cleanedPurchases||cleanedHistory||cleanedInferred)save(false);installStyles();ensurePanel();ensureDock();startDockObserver();installEvents();restartPolling();if(apiKey())ensureCatalog(false).then(()=>{save(false);render();}).catch(()=>{});render();}"
new_boot="function boot(){const cleanedPurchases=purgePreWhitelistPurchases(),cleanedHistory=purgePreTrackingEvents(),cleanedInferred=migrateInferredPersonal();if(cleanedPurchases||cleanedHistory||cleanedInferred)save(false);installStyles();ensurePanel();ensureDock();startDockObserver();installEvents();restartPolling();migrateLegacyRecoverySnapshots().then(()=>{if(panelOpen)render();}).catch(()=>{});if(apiKey())ensureCatalog(false).then(()=>{save(false);render();}).catch(()=>{});render();}"
if old_boot not in s: raise SystemExit('boot anchor not found')
s=s.replace(old_boot,new_boot,1)

p.write_text(s)
