from pathlib import Path
import re
p=Path('FactionLedgerIQ.user.js')
s=p.read_text()
s=s.replace('// @version      1.2.12','// @version      1.2.13',1)
s=s.replace("const VERSION='1.2.12';","const VERSION='1.2.13';",1)

# Settings: remember manually tracked non-whitelist Display items.
s=s.replace("settings:{playerName:'',playerId:'',factionName:'',apiKey:'',apiPolling:true,apiPollSeconds:15,displayTracking:false,showAllFactionItems:false},","settings:{playerName:'',playerId:'',factionName:'',apiKey:'',apiPolling:true,apiPollSeconds:15,displayTracking:false,showAllFactionItems:false,displayTrackedItems:[]},",1)

# Display helper/reconciliation rules v3.
s=s.replace("function displayRelevant(id){id=String(id||'');if(!id)return false;if(whitelist(id,itemName(id)))return true;return activeLots().some(l=>String(l.itemId)===id&&l.owner===F&&(l.location===INV||l.location===DISP));}","function manualDisplayItem(id){id=String(id||'');const a=Array.isArray(state.settings.displayTrackedItems)?state.settings.displayTrackedItems:[];return a.find(x=>String(x&&x.itemId||'')===id)||null;}\nfunction displayRelevant(id){id=String(id||'');if(!id)return false;if(whitelist(id,itemName(id))||manualDisplayItem(id))return true;return activeLots().some(l=>String(l.itemId)===id&&l.owner===F&&(l.location===INV||l.location===DISP));}",1)

# Replace rules v2 seed/reconcile with v3: whitelist + manually tracked Display items + faction stock.
pat=r"function seedDisplayRules\(actual\)\{.*?\nasync function reconcileDisplayCase\(\)\{.*?\n\}\n\nfunction factionPart"
new=r'''function seedDisplayRules(actual){const snap=displaySnapshotState(),now=new Date().toISOString();let changed=convertWhitelistedPersonalDisplay(),managed=new Map();for(const w of state.whitelist||[])if(w&&w.itemId)managed.set(String(w.itemId),w.itemName||itemName(w.itemId));for(const x of (Array.isArray(state.settings.displayTrackedItems)?state.settings.displayTrackedItems:[]))if(x&&x.itemId)managed.set(String(x.itemId),x.itemName||itemName(x.itemId));for(const [id,name] of managed){const physical=Math.max(0,Number(actual[id]||0)),tracked=Math.max(0,balance(id,F,DISP));if(physical>tracked){addLot({itemId:id,itemName:name,owner:F,location:DISP,qty:physical-tracked,sourceType:'DISPLAY_BASELINE',sourceRef:'',costBasisKnown:false,mvAtSource:mv(id),createdAt:now,notes:'Managed item already present in Display Case when faction-display tracking baseline was established.'});changed=true;}}
 const relevant={};for(const id of new Set([...managed.keys(),...activeLots().filter(l=>l.owner===F&&(l.location===INV||l.location===DISP)).map(l=>String(l.itemId))]))if(id)relevant[id]=Math.max(0,Number(actual[id]||0));snap.counts=relevant;snap.initializedAt=snap.initializedAt||now;snap.updatedAt=now;snap.rulesVersion=3;return changed;}
async function reconcileDisplayCase(){if(!state.settings.displayTracking||!apiKey())return false;const payload=await apiFetch('user',{selections:'display'}),actual=displayCountsFromApi(payload),snap=displaySnapshotState(),now=new Date().toISOString();if(Number(snap.rulesVersion||0)!==3)return seedDisplayRules(actual);const managedIds=[...(state.whitelist||[]).map(w=>String(w&&w.itemId||'')),...(Array.isArray(state.settings.displayTrackedItems)?state.settings.displayTrackedItems:[]).map(x=>String(x&&x.itemId||''))].filter(Boolean),relevantIds=new Set([...managedIds,...activeLots().filter(l=>l.owner===F&&(l.location===INV||l.location===DISP)).map(l=>String(l.itemId))]),prev=snap.counts||{},next={};let changed=false;for(const id of relevantIds){const physical=Math.max(0,Number(actual[id]||0)),before=Math.max(0,Number(prev[id]||0)),delta=physical-before;next[id]=physical;if(delta>0){const managed=!!whitelist(id,itemName(id))||!!manualDisplayItem(id),fAvail=balance(id,F,INV),pAvail=managed?balance(id,P,INV):0,movable=Math.min(delta,fAvail+pAvail);if(movable>0){const m=moveToFactionDisplay(id,movable,{timestamp:now,apiVerified:true,verificationSource:'DISPLAY_SNAPSHOT',displayReconcileMode:'DELTA'});m.notes=managed?'Managed Display increase reconciled from Torn API; Display ownership is Faction.':'Faction-owned Display increase reconciled from Torn API.';changed=true;}const remainder=delta-movable;if(remainder>0&&managed){addLot({itemId:id,itemName:itemName(id),owner:F,location:DISP,qty:remainder,sourceType:'DISPLAY_MANAGED_INTAKE',sourceRef:'',costBasisKnown:false,mvAtSource:mv(id),createdAt:now,notes:'Managed Display Case increase with no tracked source; classified as faction-owned by Display rule.'});changed=true;}}else if(delta<0){const tracked=Math.max(0,balance(id,F,DISP)),q=Math.min(-delta,tracked);if(q>0){const m=moveFromFactionDisplay(id,q,{timestamp:now,apiVerified:true,verificationSource:'DISPLAY_SNAPSHOT',displayReconcileMode:'DELTA'});m.notes='Faction-owned Display decrease reconciled from Torn API; item is now faction-owned in Personal Inventory location.';changed=true;}}}
snap.counts=next;snap.updatedAt=now;return changed;}

function correctExistingDisplaySource(id,qty){id=String(id||'');qty=Math.max(1,Number(qty||1));if(qty>balance(id,P,INV))throw new Error('Not enough tracked personal stock for this correction');if(qty>balance(id,F,DISP))throw new Error('Not enough existing faction Display stock for this correction');const m={id:uid('MOV'),type:'DISPLAY_SOURCE_CORRECTION',itemId:id,itemName:itemName(id),qty,from:INV,to:DISP,timestamp:new Date().toISOString(),apiVerified:false,apiLogIds:[],mvEachFrozen:mv(id),allocations:[],claimIds:[],receiptBatchId:'',status:'ACTIVE',notes:'One-time correction: existing faction Display stock was already counted, so tracked Personal stock was reduced without increasing Display quantity.'},pr=consume(id,P,INV,qty,m.id);if(pr.unresolved)throw new Error('Could not apply Display source correction');m.allocations=pr.allocations;state.movements.push(m);return m;}

function factionPart'''
ns,n=re.subn(pat,new,s,flags=re.S)
if n!=1: raise SystemExit(f'display seed/reconcile replace count {n}')
s=ns

# Inventory rows: only items with actual tracked stock. Whitelist alone must not create an empty card.
pat=r"function inventoryRows\(\)\{.*?\nfunction movementCard\(m\)"
new=r'''function inventoryRows(){const map=new Map();activeLots().forEach(l=>{if(!state.settings.displayTracking&&l.location===DISP)return;if(l.location===DISP&&l.owner!==F)return;const k=String(l.itemId);if(!map.has(k))map.set(k,{itemId:k,itemName:l.itemName||itemName(k),personal:0,faction:0,factionDisplay:0,mv:mv(k)});const r=map.get(k);if(l.location===INV&&l.owner===P)r.personal+=Number(l.qtyRemaining||0);if(l.location===INV&&l.owner===F)r.faction+=Number(l.qtyRemaining||0);if(l.location===DISP&&l.owner===F)r.factionDisplay+=Number(l.qtyRemaining||0);});return Array.from(map.values()).sort((a,b)=>a.itemName.localeCompare(b.itemName));}
function movementCard(m)'''
ns,n=re.subn(pat,new,s,flags=re.S)
if n!=1: raise SystemExit(f'inventoryRows replace count {n}')
s=ns

# Inventory Display section: manual non-whitelist tracking + one-time source correction.
old='''${state.settings.displayTracking?`<div class="fliq-section"><div class="fliq-section-title"><span>Display Case Tracking</span></div><div class="fliq-muted">Automatic. LedgerIQ only tracks whitelisted items and faction-owned items moved from the Armory. Display Case stock tracked here is always faction-owned.</div></div>`:''}`;}`'''
new='''${state.settings.displayTracking?`<div class="fliq-section"><div class="fliq-section-title"><span>Display Case Tracking</span></div><div class="fliq-muted">Automatic for whitelisted items and faction-owned stock from the Armory. Any Display stock tracked here is faction-owned. Other Display Case items are ignored unless you add them below.</div><div class="fliq-row" style="margin-top:8px">${itemSearchField('fliq-display-track-item','Add non-whitelisted Display item')}<button class="fliq-btn" data-fliq="add-display-track">Track</button></div><div class="fliq-list">${(Array.isArray(state.settings.displayTrackedItems)?state.settings.displayTrackedItems:[]).map(x=>`<div class="fliq-list-item"><div class="fliq-item-top"><div><b>${esc(x.itemName||itemName(x.itemId))}</b><div class="fliq-muted">Faction-owned when present in Display</div></div><button class="fliq-btn fliq-btn-small" data-fliq="remove-display-track" data-id="${esc(x.itemId)}">Remove</button></div></div>`).join('')}</div></div><div class="fliq-section"><div class="fliq-section-title"><span>Existing Display Correction</span><span class="fliq-muted">One-time only</span></div><div class="fliq-muted">Use this only when an item was physically moved from Personal Inventory to Display before automatic Display tracking was active. It reduces the tracked Personal count without adding another Display item.</div><div class="fliq-row fliq-form-row">${itemSearchField('fliq-display-correct-item','Item')}<input id="fliq-display-correct-qty" class="fliq-input" type="number" min="1" placeholder="Qty"></div><div class="fliq-actions"><button class="fliq-btn" data-fliq="correct-display-source">Correct Personal → Existing Display</button></div></div>`:''}`;}`'''
if old not in s: raise SystemExit('inventory Display section anchor missing')
s=s.replace(old,new,1)

# Make Add Current text explicit: rows require actual stock; whitelist alone doesn't list an item.
s=s.replace('Add only the personal or faction-owned stock you want LedgerIQ to know about.','Add the personal or faction-owned stock you want LedgerIQ to track. Whitelisting an item by itself does not create an Inventory row.',1)

# Actions for manual Display tracking and one-time correction.
needle="if(a==='add-opening'){const i=parseItem(document.getElementById('fliq-open-item').value),q=Number(document.getElementById('fliq-open-qty').value||0),owner=document.getElementById('fliq-open-owner').value,loc=document.getElementById('fliq-open-location').value;if(!i||!Number.isInteger(q)||q<=0){toast('Choose an item and whole quantity');return;}addLot({itemId:i.id,itemName:i.name,owner,location:loc,qty:q,sourceType:'OPENING',costBasisKnown:false,mvAtSource:mv(i.id),notes:'Opening stock entered manually.'});save();toast('Stock added');return;}"
insert=needle+"if(a==='add-display-track'){const i=parseItem(document.getElementById('fliq-display-track-item').value);if(!i||!i.id){toast('Choose an item');return;}if(whitelist(i.id,i.name)){toast('That item is whitelisted and already tracks Display automatically');return;}if(!Array.isArray(state.settings.displayTrackedItems))state.settings.displayTrackedItems=[];if(!state.settings.displayTrackedItems.some(x=>String(x.itemId)===String(i.id)))state.settings.displayTrackedItems.push({itemId:String(i.id),itemName:i.name,addedAt:new Date().toISOString()});save(false);try{await reconcileDisplayCase();save();toast('Display item added and synced');}catch(e){save();toast('Display item added; sync failed: '+String(e&&e.message||e));}return;}if(a==='remove-display-track'){state.settings.displayTrackedItems=(Array.isArray(state.settings.displayTrackedItems)?state.settings.displayTrackedItems:[]).filter(x=>String(x.itemId)!==String(t.dataset.id||''));save();toast('Display tracking rule removed');return;}if(a==='correct-display-source'){const i=parseItem(document.getElementById('fliq-display-correct-item').value),q=Number(document.getElementById('fliq-display-correct-qty').value||0);if(!i||!Number.isInteger(q)||q<=0){toast('Choose an item and whole quantity');return;}try{correctExistingDisplaySource(i.id,q);save();toast('Existing Display source corrected');}catch(e){toast(String(e&&e.message||e));}return;}"
if needle not in s: raise SystemExit('add-opening action anchor missing')
s=s.replace(needle,insert,1)

p.write_text(s)
