from pathlib import Path

p=Path('FactionLedgerIQ.user.js')
s=p.read_text()

s=s.replace('// @version      1.2.0','// @version      1.2.1',1)
s=s.replace("const VERSION='1.2.0';","const VERSION='1.2.1';",1)

old="function seen(id){return !!id&&state.processedLogIds.includes(String(id));}\nfunction remember(id){id=String(id||'');if(!id||seen(id))return;state.processedLogIds.push(id);if(state.processedLogIds.length>2500)state.processedLogIds=state.processedLogIds.slice(-2500);}"
new="function seen(id){return !!id&&state.processedLogIds.includes(String(id));}\nfunction recordedLog(id){id=String(id||'');if(!id)return false;return state.lots.some(l=>String(l.sourceRef||'')===id)||state.pendingTransfers.some(t=>String(t.apiLogId||'')===id)||state.movements.some(m=>Array.isArray(m.apiLogIds)&&m.apiLogIds.map(String).includes(id));}\nfunction handledLog(id){return seen(id)||recordedLog(id);}\nfunction remember(id){id=String(id||'');if(!id||seen(id))return;state.processedLogIds.push(id);if(state.processedLogIds.length>2500)state.processedLogIds=state.processedLogIds.slice(-2500);}"
if old not in s: raise SystemExit('seen block not found')
s=s.replace(old,new,1)

s=s.replace("if(!id||seen(id))continue;const d=log&&log.data", "if(!id||handledLog(id))continue;const d=log&&log.data",1)
s=s.replace("if(!id||seen(id))continue;if(!logAfterTrackingStart(log))", "if(!id||handledLog(id))continue;if(!logAfterTrackingStart(log))",1)
s=s.replace("if(ids.every(seen))return;", "if(ids.every(handledLog))return;",1)
s=s.replace("if(!id||seen(id))continue;if(!logAfterTrackingStart(log))", "if(!id||handledLog(id))continue;if(!logAfterTrackingStart(log))",1)

old_import="async function importReceipt(text){const p=extractPayload(text);if(p.kind==='PAYMENT'){let n=0;p.claims.forEach(x=>{const c=claimById(x.id);if(!c||c.status==='VOID')return;c.status='REIMBURSED';c.reimbursedAt=p.paidAt||p.generatedAt||new Date().toISOString();c.reimbursementBatchId=p.batchId;n++;});save();toast(n+' claim(s) marked reimbursed');return;}if(p.kind!=='MOVEMENT')throw new Error('Unsupported LedgerIQ receipt');const verification=await verifyMovementPayload(p),statuses=p.claims.map(c=>{const old=state.auditClaims.find(a=>a.claimId===c.id),m=p.movements.find(x=>x.movementId===c.movementId),v=m?verification[m.movementId]:'UNVERIFIED';let status='NEW',reviewReason='',manualEligible=false;if(old&&old.status==='PAID'){status='ALREADY_PAID';reviewReason='Claim ID is already recorded as paid';}else if(old&&Number(old.amount||0)!==Number(c.amount||0)){status='REVIEW';reviewReason='Claim amount conflicts with existing audit history';}else if(v==='UNVERIFIED'||v==='MEMBER_VERIFIED'){status='REVIEW';reviewReason=v==='MEMBER_VERIFIED'?'Member API verified; leadership API could not independently confirm':'Leadership API could not independently confirm';manualEligible=true;}return{claim:c,existing:old,status,verification:v,reviewReason,manualEligible};});currentAudit={payload:p,verification,claimStatuses:statuses};activeTab='audit';render();}"
new_import="async function importReceipt(text){const p=extractPayload(text);if(p.kind==='PAYMENT'){if(!p.batchId||!Array.isArray(p.claims)||!p.claims.length)throw new Error('Reimbursement receipt is missing payment details');const localPlayer=String(state.settings.playerId||''),receiptPlayer=String(p.member&&p.member.id||'');if(localPlayer&&receiptPlayer&&localPlayer!==receiptPlayer)throw new Error('This reimbursement receipt belongs to a different player');const matches=[];for(const x of p.claims){const c=claimById(x.id);if(!c||c.status==='VOID')throw new Error('Claim '+String(x.id||'')+' was not found in this LedgerIQ');if(Number(x.amount||0)!==Number(c.amount||0))throw new Error('Claim '+c.id+' amount does not match');if(x.itemId!=null&&String(x.itemId)!==String(c.itemId))throw new Error('Claim '+c.id+' item does not match');if(x.qty!=null&&Number(x.qty)!==Number(c.qty))throw new Error('Claim '+c.id+' quantity does not match');matches.push({x,c});}let n=0,dup=0;for(const r of matches){const c=r.c;if(c.status==='REIMBURSED'){dup++;continue;}c.status='REIMBURSED';c.reimbursedAt=p.paidAt||p.generatedAt||new Date().toISOString();c.reimbursementBatchId=p.batchId;n++;}if(n)save();else render();toast(n?`${n} claim(s) marked reimbursed${dup?` · ${dup} already closed`:''}`:`Receipt already imported · ${dup} claim(s) already closed`);return;}if(p.kind!=='MOVEMENT')throw new Error('Unsupported LedgerIQ receipt');if(!p.batchId||!Array.isArray(p.movements)||!Array.isArray(p.claims))throw new Error('Movement receipt is incomplete');const receiptClaimIds=p.claims.map(c=>String(c.id||''));if(new Set(receiptClaimIds).size!==receiptClaimIds.length)throw new Error('Movement receipt contains duplicate Claim IDs');const verification=await verifyMovementPayload(p),statuses=p.claims.map(c=>{const old=state.auditClaims.find(a=>a.claimId===c.id),m=p.movements.find(x=>x.movementId===c.movementId),v=m?verification[m.movementId]:'UNVERIFIED';let status='NEW',reviewReason='',manualEligible=false;if(old&&old.status==='PAID'){status='ALREADY_PAID';reviewReason='Claim ID is already recorded as paid';}else if(old&&Number(old.amount||0)!==Number(c.amount||0)){status='REVIEW';reviewReason='Claim amount conflicts with existing audit history';}else if(v==='UNVERIFIED'||v==='MEMBER_VERIFIED'){status='REVIEW';reviewReason=v==='MEMBER_VERIFIED'?'Member API verified; leadership API could not independently confirm':'Leadership API could not independently confirm';manualEligible=true;}return{claim:c,existing:old,status,verification:v,reviewReason,manualEligible};});currentAudit={payload:p,verification,claimStatuses:statuses};activeTab='audit';render();}"
if old_import not in s: raise SystemExit('importReceipt block not found')
s=s.replace(old_import,new_import,1)

old_pay="const p=currentAudit.payload,manual=mode==='manual',payable=currentAudit.claimStatuses.filter(r=>manual?(r.status==='REVIEW'&&r.manualEligible):r.status==='NEW');"
new_pay="const p=currentAudit.payload,manual=mode==='manual',payable=currentAudit.claimStatuses.filter(r=>(manual?(r.status==='REVIEW'&&r.manualEligible):r.status==='NEW')&&!state.auditClaims.some(a=>a.claimId===r.claim.id&&a.status==='PAID'));"
if old_pay not in s: raise SystemExit('payable block not found')
s=s.replace(old_pay,new_pay,1)

p.write_text(s)
