from pathlib import Path

p = Path('FactionLedgerIQ.user.js')
s = p.read_text()

s = s.replace('// @version      1.0.4', '// @version      1.0.5')
s = s.replace("const VERSION='1.0.4';", "const VERSION='1.0.5';")

old = "function purgePreTrackingEvents(){const start=trackingStartMs();if(!start)return false;let changed=false;const doomed=new Set();(state.movements||[]).forEach(m=>{if(!m||m.status==='VOID'||!['ARMORY_IN','ARMORY_OUT'].includes(m.type)||m.receiptBatchId)return;const ts=new Date(m.timestamp||0).getTime();if(!(Number.isFinite(ts)&&ts<start))return;const claims=(m.claimIds||[]).map(claimById).filter(Boolean),protectedClaim=claims.some(c=>c.status==='SUBMITTED'||c.status==='REIMBURSED');if(protectedClaim)return;m.status='VOID';m.voidedAt=new Date().toISOString();m.voidReason='Movement occurred before LedgerIQ V1 tracking began';doomed.add(m.id);claims.forEach(c=>{if(c.status==='OPEN'){c.status='VOID';c.voidedAt=new Date().toISOString();c.voidReason='Parent movement occurred before LedgerIQ V1 tracking began';}});changed=true;});(state.lots||[]).forEach(l=>{if(!l||l.status==='VOID')return;const ts=new Date(l.createdAt||0).getTime(),pre=Number.isFinite(ts)&&ts<start,linked=doomed.has(l.sourceRef);if(l.sourceType==='ARMORY_WITHDRAWAL'&&(pre||linked)){l.status='VOID';l.qtyRemaining=0;l.voidedAt=new Date().toISOString();l.voidReason='Armory withdrawal occurred before LedgerIQ V1 tracking began';changed=true;}});(state.pendingTransfers||[]).forEach(t=>{if(!t||t.status!=='PENDING')return;const ts=new Date(t.timestamp||0).getTime();if(Number.isFinite(ts)&&ts<start){t.status='VOID';t.voidedAt=new Date().toISOString();changed=true;}});return changed;}"
new = "function purgePreTrackingEvents(){const start=trackingStartMs();if(!start)return false;let changed=false;const doomed=new Set();(state.movements||[]).forEach(m=>{if(!m||m.status==='VOID'||!['ARMORY_IN','ARMORY_OUT'].includes(m.type))return;const ts=new Date(m.timestamp||0).getTime();if(!(Number.isFinite(ts)&&ts<start))return;const claims=(m.claimIds||[]).map(claimById).filter(Boolean),protectedClaim=claims.some(c=>c.status==='SUBMITTED'||c.status==='REIMBURSED');if(protectedClaim)return;m.status='VOID';m.voidedAt=new Date().toISOString();m.voidReason='Movement occurred before LedgerIQ V1 tracking began';doomed.add(m.id);claims.forEach(c=>{if(c.status==='OPEN'){c.status='VOID';c.voidedAt=new Date().toISOString();c.voidReason='Parent movement occurred before LedgerIQ V1 tracking began';}});changed=true;});(state.lots||[]).forEach(l=>{if(!l||l.status==='VOID')return;const ts=new Date(l.createdAt||0).getTime(),pre=Number.isFinite(ts)&&ts<start,linked=doomed.has(l.sourceRef);if(l.sourceType==='ARMORY_WITHDRAWAL'&&(pre||linked)){l.status='VOID';l.qtyRemaining=0;l.voidedAt=new Date().toISOString();l.voidReason='Armory withdrawal occurred before LedgerIQ V1 tracking began';changed=true;}});(state.receiptBatches||[]).forEach(b=>{if(!b||b.status==='ARCHIVED')return;const mids=Array.isArray(b.movementIds)?b.movementIds:[];if(mids.length&&mids.every(id=>{const m=movementById(id);return m&&m.status==='VOID';})){b.status='ARCHIVED';b.archivedAt=new Date().toISOString();changed=true;}});(state.pendingTransfers||[]).forEach(t=>{if(!t||t.status!=='PENDING')return;const ts=new Date(t.timestamp||0).getTime();if(Number.isFinite(ts)&&ts<start){t.status='VOID';t.voidedAt=new Date().toISOString();changed=true;}});return changed;}"
if old not in s:
    raise SystemExit('purge function pattern not found')
s = s.replace(old, new, 1)
p.write_text(s)
