from pathlib import Path
p=Path('FactionLedgerIQ.user.js')
s=p.read_text()

s=s.replace('// @version      1.2.7','// @version      1.2.8',1)
s=s.replace("const VERSION='1.2.7';","const VERSION='1.2.8';",1)

anchor="function localMove(id,qty,from,to){id=String(id);qty=Math.max(1,Number(qty||1));const fa=balance(id,F,from),fq=Math.min(qty,fa),pq=qty-fq;if(pq>balance(id,P,from))throw new Error('Not enough tracked stock');const m={id:uid('MOV'),type:to===DISP?'DISPLAY_IN':'DISPLAY_OUT',itemId:id,itemName:itemName(id),qty,from,to,timestamp:new Date().toISOString(),apiVerified:false,apiLogIds:[],mvEachFrozen:mv(id),allocations:[],claimIds:[],receiptBatchId:'',status:'ACTIVE',notes:'Faction-owned stock allocated first.'},fr=consume(id,F,from,fq,m.id),pr=consume(id,P,from,pq,m.id);m.allocations=fr.allocations.concat(pr.allocations);state.movements.push(m);m.allocations.forEach(a=>addLot({itemId:id,itemName:m.itemName,owner:a.owner,location:to,qty:a.qty,sourceType:'LOCATION_TRANSFER',sourceRef:m.id,rootId:a.rootId,costBasisKnown:a.costBasisKnown,costEach:a.costEach,mvAtSource:a.mvAtSource}));return m;}"
addition=anchor+r'''
function displayCountsFromApi(payload){const raw=payload&&payload.display!==undefined?payload.display:[],out={};for(const e of (Array.isArray(raw)?raw:Object.values(raw||{}))){const id=String(e&&(e.ID??e.id)??'').trim(),q=Number(e&&(e.quantity??e.amount)??0);if(id&&q>0)out[id]=(out[id]||0)+q;}return out;}
async function reconcileDisplayCase(){if(!state.settings.displayTracking||!apiKey())return false;const payload=await apiFetch('user',{selections:'display'}),actual=displayCountsFromApi(payload),ids=new Set(activeLots().filter(l=>l&&(l.location===INV||l.location===DISP)).map(l=>String(l.itemId))),now=new Date().toISOString();let changed=false;for(const id of ids){const physical=Math.max(0,Number(actual[id]||0)),tracked=Math.max(0,balance(id,P,DISP)+balance(id,F,DISP)),delta=physical-tracked;if(delta>0){const available=Math.max(0,balance(id,P,INV)+balance(id,F,INV)),q=Math.min(delta,available);if(q>0){const m=localMove(id,q,INV,DISP);m.timestamp=now;m.apiVerified=true;m.verificationSource='DISPLAY_SNAPSHOT';m.notes='Display Case location reconciled from Torn API snapshot. Ownership and cost basis preserved; faction-owned stock allocated first.';changed=true;}if(delta>available)console.warn('[FLIQ] Display Case contains untracked quantity',id,delta-available);}else if(delta<0){const q=Math.min(-delta,tracked);if(q>0){const m=localMove(id,q,DISP,INV);m.timestamp=now;m.apiVerified=true;m.verificationSource='DISPLAY_SNAPSHOT';m.notes='Display Case location reconciled from Torn API snapshot. Ownership and cost basis preserved; faction-owned stock allocated first.';changed=true;}}}return changed;}'''
if anchor not in s: raise SystemExit('localMove anchor missing')
s=s.replace(anchor,addition,1)

old="async function poll(showToast=false){if(apiBusy)return;if(!apiKey()){state.diagnostics.apiStatus='API key required';if(showToast)toast('Add your Torn API key in Settings');render();return;}apiBusy=true;try{await ensureCatalog(false);const d=await apiFetch('user/log',{limit:'100'}),logs=logArray(d);state.diagnostics.lastLogCount=logs.length;await reconcilePurchases(logs);await reconcileArmory(logs);await reconcileIncoming(logs);state.diagnostics.apiStatus='Connected';state.diagnostics.lastApiError='';state.diagnostics.lastSyncAt=new Date().toISOString();save(false);if(showToast||!panelOpen)render();if(showToast)toast('Ledger synced');}catch(e){state.diagnostics.apiStatus='Error';state.diagnostics.lastApiError=String(e&&e.message||e);save(false);if(showToast||!panelOpen)render();if(showToast)toast('Sync failed: '+state.diagnostics.lastApiError);}finally{apiBusy=false;}}"
new="async function poll(showToast=false){if(apiBusy)return;if(!apiKey()){state.diagnostics.apiStatus='API key required';if(showToast)toast('Add your Torn API key in Settings');render();return;}apiBusy=true;try{await ensureCatalog(false);const d=await apiFetch('user/log',{limit:'100'}),logs=logArray(d);state.diagnostics.lastLogCount=logs.length;await reconcilePurchases(logs);await reconcileArmory(logs);await reconcileIncoming(logs);let displayError='';if(state.settings.displayTracking){try{await reconcileDisplayCase();}catch(e){displayError=String(e&&e.message||e);console.warn('[FLIQ] Display Case sync failed',e);}}state.diagnostics.apiStatus='Connected';state.diagnostics.lastApiError=displayError?('Display Case sync: '+displayError):'';state.diagnostics.lastSyncAt=new Date().toISOString();save(false);if(showToast||!panelOpen)render();if(showToast)toast(displayError?'Ledger synced; Display Case could not be read':'Ledger synced');}catch(e){state.diagnostics.apiStatus='Error';state.diagnostics.lastApiError=String(e&&e.message||e);save(false);if(showToast||!panelOpen)render();if(showToast)toast('Sync failed: '+state.diagnostics.lastApiError);}finally{apiBusy=false;}}"
if old not in s: raise SystemExit('poll block missing')
s=s.replace(old,new,1)

old="<div class=\"fliq-muted\" style=\"margin-top:4px\"><b>API use:</b> LedgerIQ uses Torn API endpoints for user logs, Torn item/market data, and faction news when your faction permissions allow it.</div>"
new="<div class=\"fliq-muted\" style=\"margin-top:4px\"><b>API use:</b> LedgerIQ uses Torn API endpoints for user logs, your Display Case contents when Display tracking is enabled, Torn item/market data, and faction news when your faction permissions allow it.</div>"
if old not in s: raise SystemExit('API disclosure line missing')
s=s.replace(old,new,1)

p.write_text(s)
# trigger
