from pathlib import Path
import re
p=Path('FactionLedgerIQ.user.js')
s=p.read_text()
s=s.replace('// @version      1.2.11','// @version      1.2.12',1)
s=s.replace("const VERSION='1.2.11';","const VERSION='1.2.12';",1)

# Replace Display movement/reconciliation block.
pat=r"function localMove\(id,qty,from,to\)\{.*?\n\nfunction factionPart\(log\)"
new=r'''function displayRelevant(id){id=String(id||'');if(!id)return false;if(whitelist(id,itemName(id)))return true;return activeLots().some(l=>String(l.itemId)===id&&l.owner===F&&(l.location===INV||l.location===DISP));}
function moveToFactionDisplay(id,qty,opts={}){id=String(id);qty=Math.max(1,Number(qty||1));const isWhite=!!whitelist(id,itemName(id)),fAvail=balance(id,F,INV),pAvail=isWhite?balance(id,P,INV):0,fq=Math.min(qty,fAvail),pq=Math.min(qty-fq,pAvail),moved=fq+pq;if(!moved)throw new Error(isWhite?'No tracked stock available to move to Display':'Only faction-owned stock can be tracked in Display');if(moved<qty&&!isWhite)throw new Error('Only faction-owned stock can be tracked in Display');const m={id:uid('MOV'),type:'DISPLAY_IN',itemId:id,itemName:itemName(id),qty:moved,from:INV,to:DISP,timestamp:opts.timestamp||new Date().toISOString(),apiVerified:opts.apiVerified===true,apiLogIds:[],mvEachFrozen:mv(id),allocations:[],claimIds:[],receiptBatchId:'',status:'ACTIVE',verificationSource:opts.verificationSource||'',displayReconcileMode:opts.displayReconcileMode||'',notes:isWhite?'Whitelisted item moved to Display; Display Case ownership is Faction.':'Faction-owned item moved to Display.'},fr=consume(id,F,INV,fq,m.id),pr=consume(id,P,INV,pq,m.id);m.allocations=fr.allocations.concat(pr.allocations);state.movements.push(m);m.allocations.forEach(a=>addLot({itemId:id,itemName:m.itemName,owner:F,location:DISP,qty:a.qty,sourceType:a.owner===P?'WHITELIST_DISPLAY_TRANSFER':'LOCATION_TRANSFER',sourceRef:m.id,rootId:a.rootId,costBasisKnown:a.costBasisKnown,costEach:a.costEach,mvAtSource:a.mvAtSource,notes:a.owner===P?'Whitelisted stock becomes faction-owned while in Display Case.':'Faction-owned stock moved to Display Case.'}));return m;}
function moveFromFactionDisplay(id,qty,opts={}){id=String(id);qty=Math.max(1,Number(qty||1));if(qty>balance(id,F,DISP))throw new Error('Not enough tracked faction-owned Display stock');const m={id:uid('MOV'),type:'DISPLAY_OUT',itemId:id,itemName:itemName(id),qty,from:DISP,to:INV,timestamp:opts.timestamp||new Date().toISOString(),apiVerified:opts.apiVerified===true,apiLogIds:[],mvEachFrozen:mv(id),allocations:[],claimIds:[],receiptBatchId:'',status:'ACTIVE',verificationSource:opts.verificationSource||'',displayReconcileMode:opts.displayReconcileMode||'',notes:'Faction-owned Display stock moved back to Personal Inventory location.'},fr=consume(id,F,DISP,qty,m.id);m.allocations=fr.allocations;state.movements.push(m);m.allocations.forEach(a=>addLot({itemId:id,itemName:m.itemName,owner:F,location:INV,qty:a.qty,sourceType:'LOCATION_TRANSFER',sourceRef:m.id,rootId:a.rootId,costBasisKnown:a.costBasisKnown,costEach:a.costEach,mvAtSource:a.mvAtSource,notes:'Faction-owned stock returned from Display Case.'}));return m;}
function displayCountsFromApi(payload){const raw=payload&&payload.display!==undefined?payload.display:[],out={};for(const e of (Array.isArray(raw)?raw:Object.values(raw||{}))){const id=String(e?(e.ID??e.id??''):'').trim(),q=Number(e?(e.quantity??e.amount??0):0);if(id&&q>0)out[id]=(out[id]||0)+q;}return out;}
function displaySnapshotState(){if(!state.displaySnapshot||typeof state.displaySnapshot!=='object')state.displaySnapshot={counts:{},initializedAt:'',updatedAt:'',rulesVersion:0};if(!state.displaySnapshot.counts||typeof state.displaySnapshot.counts!=='object')state.displaySnapshot.counts={};return state.displaySnapshot;}
function migrateLegacyDisplaySnapshot(){const rows=state.movements.filter(m=>m&&m.status!=='VOID'&&m.verificationSource==='DISPLAY_SNAPSHOT'&&m.displayReconcileMode!=='DELTA'&&!m.receiptBatchId).slice().sort((a,b)=>new Date(b.timestamp||0)-new Date(a.timestamp||0));let changed=false;for(const m of rows){const dest=String(m.to||''),src=String(m.from||''),lots=state.lots.filter(l=>l&&l.status==='OPEN'&&String(l.sourceRef||'')===String(m.id)&&String(l.location||'')===dest&&Number(l.qtyRemaining||0)>0),qty=lots.reduce((n,l)=>n+Number(l.qtyRemaining||0),0);if(qty!==Number(m.qty||0))continue;for(const l of lots){const q=Number(l.qtyRemaining||0);l.qtyRemaining=0;l.status='VOID';l.voidedAt=new Date().toISOString();l.voidReason='Legacy Display snapshot correction';addLot({itemId:l.itemId,itemName:l.itemName,owner:l.owner,location:src,qty:q,sourceType:'DISPLAY_BASELINE_CORRECTION',sourceRef:m.id,rootId:l.rootId,costBasisKnown:l.costBasisKnown,costEach:l.costEach,mvAtSource:l.mvAtSource,notes:'Returned to prior LedgerIQ location because pre-existing Display Case stock was incorrectly treated as a new movement.'});}m.status='VOID';m.voidedAt=new Date().toISOString();m.voidReason='Legacy Display snapshot reconciliation treated pre-existing Display Case stock as a new movement';changed=true;}if(changed)state.displaySnapshot={counts:{},initializedAt:'',updatedAt:'',rulesVersion:0};return changed;}
function convertWhitelistedPersonalDisplay(){let changed=false,now=new Date().toISOString();for(const l of activeLots().filter(x=>x.owner===P&&x.location===DISP&&whitelist(x.itemId,x.itemName))){const q=Number(l.qtyRemaining||0);if(!q)continue;l.qtyRemaining=0;l.status='VOID';l.voidedAt=now;l.voidReason='Display rule update: whitelisted Display Case stock is faction-owned';addLot({itemId:l.itemId,itemName:l.itemName,owner:F,location:DISP,qty:q,sourceType:'DISPLAY_RULE_CONVERSION',sourceRef:l.id,rootId:l.rootId,costBasisKnown:l.costBasisKnown,costEach:l.costEach,mvAtSource:l.mvAtSource,notes:'Whitelisted Display Case stock classified as faction-owned.'});changed=true;}return changed;}
function seedDisplayRules(actual){const snap=displaySnapshotState(),now=new Date().toISOString();let changed=convertWhitelistedPersonalDisplay();for(const w of state.whitelist||[]){const id=String(w.itemId||'');if(!id)continue;const physical=Math.max(0,Number(actual[id]||0)),tracked=Math.max(0,balance(id,F,DISP));if(physical>tracked){addLot({itemId:id,itemName:w.itemName||itemName(id),owner:F,location:DISP,qty:physical-tracked,sourceType:'DISPLAY_BASELINE',sourceRef:'',costBasisKnown:false,mvAtSource:mv(id),createdAt:now,notes:'Whitelisted item already present in Display Case when faction-display tracking baseline was established.'});changed=true;}}
 const relevant={};for(const id of new Set([...(state.whitelist||[]).map(w=>String(w.itemId||'')),...activeLots().filter(l=>l.owner===F&&(l.location===INV||l.location===DISP)).map(l=>String(l.itemId))]))if(id)relevant[id]=Math.max(0,Number(actual[id]||0));snap.counts=relevant;snap.initializedAt=snap.initializedAt||now;snap.updatedAt=now;snap.rulesVersion=2;return changed;}
async function reconcileDisplayCase(){if(!state.settings.displayTracking||!apiKey())return false;const payload=await apiFetch('user',{selections:'display'}),actual=displayCountsFromApi(payload),snap=displaySnapshotState(),now=new Date().toISOString();if(Number(snap.rulesVersion||0)!==2)return seedDisplayRules(actual);const relevantIds=new Set([...(state.whitelist||[]).map(w=>String(w.itemId||'')),...activeLots().filter(l=>l.owner===F&&(l.location===INV||l.location===DISP)).map(l=>String(l.itemId))].filter(Boolean)),prev=snap.counts||{},next={};let changed=false;for(const id of relevantIds){const physical=Math.max(0,Number(actual[id]||0)),before=Math.max(0,Number(prev[id]||0)),delta=physical-before;next[id]=physical;if(delta>0){const isWhite=!!whitelist(id,itemName(id)),fAvail=balance(id,F,INV),pAvail=isWhite?balance(id,P,INV):0,movable=Math.min(delta,fAvail+pAvail);if(movable>0){const m=moveToFactionDisplay(id,movable,{timestamp:now,apiVerified:true,verificationSource:'DISPLAY_SNAPSHOT',displayReconcileMode:'DELTA'});m.notes=isWhite?'Whitelisted Display increase reconciled from Torn API; Display ownership is Faction.':'Faction-owned Display increase reconciled from Torn API.';changed=true;}const remainder=delta-movable;if(remainder>0&&isWhite){addLot({itemId:id,itemName:itemName(id),owner:F,location:DISP,qty:remainder,sourceType:'DISPLAY_WHITELIST_INTAKE',sourceRef:'',costBasisKnown:false,mvAtSource:mv(id),createdAt:now,notes:'Whitelisted Display Case increase with no tracked source; classified as faction-owned by Display rule.'});changed=true;}}else if(delta<0){const tracked=Math.max(0,balance(id,F,DISP)),q=Math.min(-delta,tracked);if(q>0){const m=moveFromFactionDisplay(id,q,{timestamp:now,apiVerified:true,verificationSource:'DISPLAY_SNAPSHOT',displayReconcileMode:'DELTA'});m.notes='Faction-owned Display decrease reconciled from Torn API.';changed=true;}}}
snap.counts=next;snap.updatedAt=now;return changed;}

function factionPart(log)'''
ns,n=re.subn(pat,new,s,flags=re.S)
if n!=1: raise SystemExit(f'display block replace count {n}')
s=ns

# Inventory rows: only whitelisted items or tracked faction items; never raw Display contents.
pat=r"function inventoryRows\(\)\{.*?\nfunction movementCard\(m\)"
new=r'''function inventoryRows(){const map=new Map(),snap=displaySnapshotState(),physical=snap.counts||{},relevant=id=>!!whitelist(id,itemName(id))||activeLots().some(l=>String(l.itemId)===String(id)&&l.owner===F);activeLots().forEach(l=>{const k=String(l.itemId);if(!relevant(k))return;if(!state.settings.displayTracking&&l.location===DISP)return;if(!map.has(k))map.set(k,{itemId:k,itemName:l.itemName||itemName(k),personal:0,faction:0,factionDisplay:0,physicalDisplay:Number(physical[k]||0),mv:mv(k)});const r=map.get(k);if(l.location===INV&&l.owner===P)r.personal+=Number(l.qtyRemaining||0);if(l.location===INV&&l.owner===F)r.faction+=Number(l.qtyRemaining||0);if(l.location===DISP&&l.owner===F)r.factionDisplay+=Number(l.qtyRemaining||0);});(state.whitelist||[]).forEach(w=>{const k=String(w.itemId||'');if(!k||map.has(k))return;map.set(k,{itemId:k,itemName:w.itemName||itemName(k),personal:0,faction:0,factionDisplay:0,physicalDisplay:Number(physical[k]||0),mv:mv(k)});});return Array.from(map.values()).sort((a,b)=>a.itemName.localeCompare(b.itemName));}
function movementCard(m)'''
ns,n=re.subn(pat,new,s,flags=re.S)
if n!=1: raise SystemExit(f'inventoryRows replace count {n}')
s=ns

# Simplify Inventory display stat and remove manual Display Case controls; API sync owns location tracking.
s=s.replace("${state.settings.displayTracking?`<div><span>Display P / F</span><b>${r.personalDisplay.toLocaleString()} / ${r.factionDisplay.toLocaleString()}</b><small>Torn: ${Number(r.physicalDisplay||0).toLocaleString()}${r.untrackedDisplay?' · Untracked '+Number(r.untrackedDisplay).toLocaleString():''}</small></div>`:''}","${state.settings.displayTracking?`<div><span>Faction Display</span><b>${r.factionDisplay.toLocaleString()}</b></div>`:''}")
s=re.sub(r"\$\{state\.settings\.displayTracking\?`<div class=\"fliq-section\"><div class=\"fliq-section-title\"><span>Display Case</span></div>.*?</div>`:''\}","${state.settings.displayTracking?`<div class=\"fliq-section\"><div class=\"fliq-section-title\"><span>Display Case Tracking</span></div><div class=\"fliq-muted\">Automatic. LedgerIQ only tracks whitelisted items and faction-owned items moved from the Armory. Display Case stock tracked here is always faction-owned.</div></div>`:''}",s,flags=re.S)

# Manual opening stock must stay in Personal Inventory; Display is API-managed.
s=s.replace("${state.settings.displayTracking?'<select id=\"fliq-open-location\" class=\"fliq-select\"><option value=\"PERSONAL_INVENTORY\">Personal Inventory</option><option value=\"DISPLAY_CASE\">Display Case</option></select>':'<input id=\"fliq-open-location\" type=\"hidden\" value=\"PERSONAL_INVENTORY\">'}","<input id=\"fliq-open-location\" type=\"hidden\" value=\"PERSONAL_INVENTORY\">")

# Old manual display action should no longer be reachable, but keep safe semantics if a stale DOM fires it.
s=s.replace("try{localMove(i.id,q,a==='display-in'?INV:DISP,a==='display-in'?DISP:INV);save();}","try{if(a==='display-in')moveToFactionDisplay(i.id,q);else moveFromFactionDisplay(i.id,q);save();}")

p.write_text(s)
