from pathlib import Path

p=Path('FactionLedgerIQ.user.js')
s=p.read_text()

s=s.replace('// @version      1.2.3','// @version      1.2.4',1)
s=s.replace("const VERSION='1.2.3';","const VERSION='1.2.4';",1)
s=s.replace("diagnostics:{apiStatus:'Not configured',lastSyncAt:'',lastApiError:'',lastLogCount:0}","diagnostics:{apiStatus:'Not configured',lastSyncAt:'',lastApiError:'',lastLogCount:0,lastCacheRebuildAt:''}",1)

old_cache="async function clearRefreshableCache(){state.market={};itemCatalog=[];itemCatalogLoadedAt=0;state.diagnostics={...DEFAULT.diagnostics,apiStatus:apiKey()?'Cache cleared':'API key required'};save(false);if(apiKey()){try{await ensureCatalog(true);state.diagnostics.apiStatus='Connected';state.diagnostics.lastApiError='';state.diagnostics.lastSyncAt=new Date().toISOString();save();toast('Cache cleared and rebuilt');}catch(e){state.diagnostics.apiStatus='Error';state.diagnostics.lastApiError=String(e&&e.message||e);save();toast('Cache cleared; rebuild failed');}}else{save();toast('Cache cleared');}}"
new_cache="async function clearRefreshableCache(){state.market={};itemCatalog=[];itemCatalogLoadedAt=0;state.diagnostics={...DEFAULT.diagnostics,...state.diagnostics,apiStatus:apiKey()?'Cache cleared':'API key required'};save(false);if(apiKey()){try{await ensureCatalog(true);state.diagnostics.apiStatus='Connected';state.diagnostics.lastApiError='';state.diagnostics.lastSyncAt=new Date().toISOString();state.diagnostics.lastCacheRebuildAt=new Date().toISOString();save();toast('Cache rebuilt successfully');}catch(e){state.diagnostics.apiStatus='Error';state.diagnostics.lastApiError=String(e&&e.message||e);save();toast('Cache cleared; rebuild failed');}}else{state.diagnostics.lastCacheRebuildAt=new Date().toISOString();save();toast('Cache cleared');}}"
if old_cache not in s: raise SystemExit('cache function not found')
s=s.replace(old_cache,new_cache,1)

old_reset="function resetLedgerDataFromUi(){const input=document.getElementById('fliq-reset-confirm'),word=String(input&&input.value||'').trim();if(word!=='RESET')throw new Error('Type RESET exactly to reset ledger data');const previous={kind:'FactionLedgerIQPreReset',savedAt:new Date().toISOString(),state:clone(state)};localStorage.setItem(PRE_RESET_KEY,JSON.stringify(previous));const keepSettings=clone(state.settings||DEFAULT.settings),keepWhitelist=clone(state.whitelist||[]),now=new Date().toISOString();state=clone(DEFAULT);state.settings={...DEFAULT.settings,...keepSettings};state.whitelist=keepWhitelist;state.createdAt=now;state.updatedAt=now;state.diagnostics={...DEFAULT.diagnostics,apiStatus:apiKey()?'Ready to sync':'API key required'};itemCatalog=[];itemCatalogLoadedAt=0;currentAudit=null;activeTab='home';localStorage.setItem(STATE_KEY,JSON.stringify(state));restartPolling();render();toast('Ledger data reset — Undo is available in Settings');}"
new_reset="function resetLedgerDataFromUi(){const input=document.getElementById('fliq-reset-confirm'),word=String(input&&input.value||'').trim();if(word!=='RESET')throw new Error('Type RESET exactly to reset ledger data');const oldRaw=localStorage.getItem(STATE_KEY)||JSON.stringify(state),keepSettings=clone(state.settings||DEFAULT.settings),keepWhitelist=clone(state.whitelist||[]),now=new Date().toISOString(),fresh=clone(DEFAULT);fresh.settings={...DEFAULT.settings,...keepSettings};fresh.whitelist=keepWhitelist;fresh.createdAt=now;fresh.updatedAt=now;fresh.diagnostics={...DEFAULT.diagnostics,apiStatus:String(keepSettings.apiKey||'').trim()?'Ready to sync':'API key required'};localStorage.removeItem(PRE_RESET_KEY);localStorage.removeItem(STATE_KEY);try{localStorage.setItem(PRE_RESET_KEY,oldRaw);localStorage.setItem(STATE_KEY,JSON.stringify(fresh));}catch(e){localStorage.removeItem(PRE_RESET_KEY);localStorage.removeItem(STATE_KEY);localStorage.setItem(STATE_KEY,oldRaw);throw new Error('Reset could not create a recovery snapshot because device storage is full');}state=fresh;itemCatalog=[];itemCatalogLoadedAt=0;currentAudit=null;activeTab='home';restartPolling();render();toast('Ledger data reset — Undo is available in Settings');}"
if old_reset not in s: raise SystemExit('reset function not found')
s=s.replace(old_reset,new_reset,1)

old_undo="function undoLastLedgerReset(){const raw=localStorage.getItem(PRE_RESET_KEY);if(!raw)throw new Error('No pre-reset snapshot is available');let b;try{b=JSON.parse(raw);}catch(e){throw new Error('Pre-reset snapshot is unreadable');}if(!b||b.kind!=='FactionLedgerIQPreReset'||!b.state)throw new Error('Pre-reset snapshot is invalid');const existingKey=apiKey();state=hydrateState(b.state,existingKey);state.updatedAt=new Date().toISOString();localStorage.setItem(STATE_KEY,JSON.stringify(state));localStorage.removeItem(PRE_RESET_KEY);currentAudit=null;restartPolling();render();toast('Last ledger reset undone');}"
new_undo="function undoLastLedgerReset(){const raw=localStorage.getItem(PRE_RESET_KEY);if(!raw)throw new Error('No pre-reset snapshot is available');let b;try{b=JSON.parse(raw);}catch(e){throw new Error('Pre-reset snapshot is unreadable');}const snapshot=b&&b.kind==='FactionLedgerIQPreReset'?b.state:b;if(!snapshot||typeof snapshot!=='object')throw new Error('Pre-reset snapshot is invalid');const existingKey=apiKey(),currentRaw=localStorage.getItem(STATE_KEY)||JSON.stringify(state),restored=hydrateState(snapshot,existingKey);restored.updatedAt=new Date().toISOString();localStorage.removeItem(STATE_KEY);localStorage.removeItem(PRE_RESET_KEY);try{localStorage.setItem(STATE_KEY,JSON.stringify(restored));}catch(e){localStorage.setItem(PRE_RESET_KEY,raw);localStorage.setItem(STATE_KEY,currentRaw);throw new Error('Undo could not restore the ledger because device storage is full');}state=restored;currentAudit=null;restartPolling();render();toast('Last ledger reset undone');}"
if old_undo not in s: raise SystemExit('undo reset function not found')
s=s.replace(old_undo,new_undo,1)

anchor='<div class="fliq-section"><div class="fliq-section-title"><span>Recovery / Reset</span></div><div class="fliq-muted">Clear & Rebuild Cache only refreshes market/catalog data'
replacement='<div class="fliq-section"><div class="fliq-section-title"><span>Recovery / Reset</span></div><div class="fliq-muted">${state.diagnostics.lastCacheRebuildAt?\'Last cache rebuild: \'+esc(fmt(state.diagnostics.lastCacheRebuildAt)):\'Cache has not been rebuilt manually yet.\'}</div><div class="fliq-muted" style="margin-top:7px">Clear & Rebuild Cache only refreshes market/catalog data'
if anchor not in s: raise SystemExit('recovery UI anchor not found')
s=s.replace(anchor,replacement,1)

p.write_text(s)
