from pathlib import Path
p=Path('FactionLedgerIQ.user.js')
s=p.read_text()
s=s.replace('// @version      1.2.5','// @version      1.2.6',1)
s=s.replace("const VERSION='1.2.5';","const VERSION='1.2.6';",1)
old='''<div class="fliq-section"><div class="fliq-section-title"><span>Torn API</span></div><input id="fliq-set-api" class="fliq-input" type="password" value="${esc(state.settings.apiKey)}" placeholder="Torn API key"><div class="fliq-row"><label><input id="fliq-set-poll" type="checkbox" ${state.settings.apiPolling?'checked':''}> Auto sync</label><input id="fliq-set-seconds" class="fliq-input" style="width:80px" type="number" min="10" value="${esc(state.settings.apiPollSeconds)}"><span class="fliq-muted">seconds</span></div></div>'''
new='''<div class="fliq-section"><div class="fliq-section-title"><span>Torn API</span></div><input id="fliq-set-api" class="fliq-input" type="password" value="${esc(state.settings.apiKey)}" placeholder="Torn API key"><div class="fliq-list-item" style="margin-top:8px"><b>API & Data Handling</b><div class="fliq-muted" style="margin-top:5px"><b>Storage:</b> LedgerIQ data and your API key are stored only on this device. Active data uses browser local storage; recovery snapshots use browser IndexedDB.</div><div class="fliq-muted" style="margin-top:4px"><b>Sharing:</b> LedgerIQ does not send your stored data or API key to third parties. The API key is sent only to Torn's official API.</div><div class="fliq-muted" style="margin-top:4px"><b>Purpose:</b> Faction inventory ownership, reimbursement tracking, raffle intake, receipts, and leadership auditing.</div><div class="fliq-muted" style="margin-top:4px"><b>API use:</b> LedgerIQ uses Torn API endpoints for user logs, Torn item/market data, and faction news when your faction permissions allow it.</div><div class="fliq-muted" style="margin-top:4px"><b>Access:</b> Use the lowest-access Torn API key that provides the selections LedgerIQ needs. LedgerIQ does not require a Full Access key.</div></div><div class="fliq-row"><label><input id="fliq-set-poll" type="checkbox" ${state.settings.apiPolling?'checked':''}> Auto sync</label><input id="fliq-set-seconds" class="fliq-input" style="width:80px" type="number" min="10" value="${esc(state.settings.apiPollSeconds)}"><span class="fliq-muted">seconds</span></div></div>'''
if old not in s:
    raise SystemExit('API settings block not found')
s=s.replace(old,new,1)
p.write_text(s)
