from pathlib import Path

p=Path('FactionLedgerIQ.user.js')
s=p.read_text()

s=s.replace('// @version      1.4.2','// @version      1.4.3',1)
s=s.replace("const VERSION='1.4.2';","const VERSION='1.4.3';",1)

start=s.index('function compactAuditPayload(')
end=s.index('function movementPayload(', start)
old=s[start:end]
new=r'''function b36(v){return Math.max(0,Math.round(Number(v||0))).toString(36);}
function u36(v){const n=parseInt(String(v||'0'),36);return Number.isFinite(n)?n:0;}
function cutPrefix(v,p){v=String(v||'');return v.startsWith(p)?v.slice(p.length):v;}
function wireName(v){return encodeURIComponent(String(v||''));}
function unwireName(v){try{return decodeURIComponent(String(v||''));}catch(e){return String(v||'');}}
function legacyDecodePayload(code){let x=String(code||'').trim().replace(/-/g,'+').replace(/_/g,'/');while(x.length%4)x+='=';const obj=JSON.parse(decodeURIComponent(escape(atob(x))));if(!obj||typeof obj!=='object'||!obj.k)return obj;if(obj.k==='M'){const movements=(obj.m||[]).map((r,i)=>({movementId:'R'+i,type:r[0]||'',timestamp:r[1]||'',itemId:String(r[2]||''),itemName:r[3]||'',qty:Number(r[4]||0),from:'PERSONAL_INVENTORY',to:r[5]||'',apiVerified:!!r[6],apiLogIds:[],verificationSource:r[7]||'',allocations:[],claimIds:[]})),verification={};movements.forEach((m,i)=>{const r=(obj.m||[])[i]||[];verification[m.movementId]=r[8]||(m.type==='DISPLAY_IN'&&m.apiVerified?'VERIFIED_DISPLAY':m.apiVerified?'MEMBER_VERIFIED':'UNVERIFIED');});const claims=(obj.c||[]).map(r=>{const i=Number(r[1]||0),m=movements[i]||{},c={id:r[0]||'',movementId:m.movementId||('R'+i),itemId:m.itemId||'',itemName:m.itemName||'',qty:Number(r[2]||0),paidEach:Number(r[3]||0),costBasisKnown:!!r[4],mvAtPurchase:Number(r[5]||0),mvEachFrozen:Number(r[6]||0),amount:Number(r[7]||0),status:r[8]||'SUBMITTED',destination:m.to||'FACTION_ARMORY',verification:r[9]||verification[m.movementId]||''};if(m.claimIds)m.claimIds.push(c.id);return c;});return{kind:'MOVEMENT',version:obj.v||'',batchId:obj.b||'',generatedAt:obj.g||'',player:{name:obj.p&&obj.p[0]||'',id:obj.p&&obj.p[1]||''},factionName:obj.f||'',movements,claims,verification};}if(obj.k==='P'){const claims=(obj.c||[]).map(r=>({id:r[0]||'',itemId:String(r[1]||''),itemName:r[2]||'',qty:Number(r[3]||0),paidEach:Number(r[4]||0),costBasisKnown:!!r[5],mvAtPurchase:Number(r[6]||0),mvEachFrozen:Number(r[7]||0),amount:Number(r[8]||0),destination:'FACTION_ARMORY',verification:r[9]||''}));return{kind:'PAYMENT',version:obj.v||'',batchId:obj.b||'',sourceReceiptBatchId:obj.s||'',generatedAt:obj.g||'',paidAt:obj.d||'',factionName:obj.f||'',member:{name:obj.p&&obj.p[0]||'',id:obj.p&&obj.p[1]||''},leadership:{name:obj.l&&obj.l[0]||'',id:obj.l&&obj.l[1]||''},verificationMethod:obj.vm||'',claims,total:claims.reduce((n,c)=>n+Number(c.amount||0),0)};}return obj;}
function encodePayload(p){if(p&&p.kind==='PAYMENT'){const claims=(p.claims||[]).map(c=>[cutPrefix(c.id,'CLM-'),b36(c.itemId),b36(c.qty),b36(c.amount)].join(',')).join(';');return['P1',cutPrefix(p.batchId,'PAY-'),cutPrefix(p.sourceReceiptBatchId,'BATCH-'),b36(p.member&&p.member.id),claims].join('|');}if(p&&p.kind==='MOVEMENT'){const moves=p.movements||[],idx=new Map(moves.map((m,i)=>[String(m.movementId||''),i])),ms=moves.map(m=>[(m.type==='DISPLAY_IN'?'D':'A'),b36(Math.floor(new Date(m.timestamp||0).getTime()/1000)),b36(m.itemId),b36(m.qty),m.apiVerified?1:0].join(',')).join(';'),cs=(p.claims||[]).map(c=>[cutPrefix(c.id,'CLM-'),b36(idx.get(String(c.movementId||''))||0),b36(c.qty),b36(c.paidEach),c.costBasisKnown?1:0,b36(c.mvAtPurchase),b36(c.mvEachFrozen),b36(c.amount)].join(',')).join(';');return['M1',cutPrefix(p.batchId,'BATCH-'),wireName(p.player&&p.player.name||''),b36(p.player&&p.player.id),ms,cs].join('|');}return btoa(unescape(encodeURIComponent(JSON.stringify(p)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function decodePayload(code){code=String(code||'').trim();if(code.startsWith('P1|')){const a=code.split('|'),claims=String(a[4]||'').split(';').filter(Boolean).map(x=>{const r=x.split(','),id='CLM-'+r[0],itemId=String(u36(r[1])),qty=u36(r[2]),amount=u36(r[3]);return{id,itemId,itemName:itemName(itemId),qty,paidEach:0,costBasisKnown:false,mvAtPurchase:0,mvEachFrozen:qty?Math.round(amount/qty):0,amount,destination:'FACTION_ARMORY',verification:''};});return{kind:'PAYMENT',version:'1.4.3+',batchId:'PAY-'+(a[1]||''),sourceReceiptBatchId:'BATCH-'+(a[2]||''),generatedAt:'',paidAt:'',factionName:state.settings.factionName||'',member:{name:'',id:String(u36(a[3]))},leadership:{name:'',id:''},verificationMethod:'API_VERIFIED',claims,total:claims.reduce((n,c)=>n+Number(c.amount||0),0)};}if(code.startsWith('M1|')){const a=code.split('|'),moves=String(a[4]||'').split(';').filter(Boolean).map((x,i)=>{const r=x.split(','),type=r[0]==='D'?'DISPLAY_IN':'ARMORY_IN',itemId=String(u36(r[2])),apiVerified=r[4]==='1';return{movementId:'R'+i,type,timestamp:new Date(u36(r[1])*1000).toISOString(),itemId,itemName:itemName(itemId),qty:u36(r[3]),from:'PERSONAL_INVENTORY',to:type==='DISPLAY_IN'?'DISPLAY_CASE':'FACTION_ARMORY',apiVerified,apiLogIds:[],verificationSource:type==='DISPLAY_IN'&&apiVerified?'DISPLAY_SNAPSHOT':'',allocations:[],claimIds:[]};}),verification={};moves.forEach(m=>verification[m.movementId]=m.type==='DISPLAY_IN'&&m.apiVerified?'VERIFIED_DISPLAY':m.apiVerified?'MEMBER_VERIFIED':'UNVERIFIED');const claims=String(a[5]||'').split(';').filter(Boolean).map(x=>{const r=x.split(','),mi=u36(r[1]),m=moves[mi]||{},c={id:'CLM-'+r[0],movementId:m.movementId||('R'+mi),itemId:m.itemId||'',itemName:m.itemName||'',qty:u36(r[2]),paidEach:u36(r[3]),costBasisKnown:r[4]==='1',mvAtPurchase:u36(r[5]),mvEachFrozen:u36(r[6]),amount:u36(r[7]),status:'SUBMITTED',destination:m.to||'FACTION_ARMORY',verification:verification[m.movementId]||''};if(m.claimIds)m.claimIds.push(c.id);return c;});return{kind:'MOVEMENT',version:'1.4.3+',batchId:'BATCH-'+(a[1]||''),generatedAt:'',player:{name:unwireName(a[2]||''),id:String(u36(a[3]))},factionName:state.settings.factionName||'',movements:moves,claims,verification};}return legacyDecodePayload(code);}
function extractPayload(text){text=String(text||'');let m=text.match(/FLIQ:([^|\s]+(?:\|[^\s|]*){3,5})/);if(m)return decodePayload(m[1]);m=text.match(/FLIQ-AUDIT:([A-Za-z0-9_-]+)/);if(!m)throw new Error('No FactionLedgerIQ verification code found');return legacyDecodePayload(m[1]);}
'''
s=s[:start]+new+s[end:]

s=s.replace("`||FLIQ-AUDIT:${encodePayload(p)}||`","`||FLIQ:${encodePayload(p)}||`",2)

old="const existingPay=(state.paymentBatches||[]).find(b=>String(b.id||'')===String(p.batchId||'')),payText=paymentReceipt(p);"
new="const existingPay=(state.paymentBatches||[]).find(b=>String(b.id||'')===String(p.batchId||'')),payText=String(text||'').trim()||paymentReceipt(p);"
assert old in s, 'payment import payText block not found'
s=s.replace(old,new,1)

old="function openPaymentBatch(id){const b=(state.paymentBatches||[]).find(x=>String(x.id||'')===String(id||''));if(!b){toast('Payment receipt not found');return;}const p=paymentPayloadFromBatch(b);if(!p){toast('Payment receipt can no longer be reconstructed');return;}const text=paymentReceipt(p);b.payload=p;b.receiptText=text;save(false);showReceipt('Discord Payment Receipt',text);}"
new="function openPaymentBatch(id){const b=(state.paymentBatches||[]).find(x=>String(x.id||'')===String(id||''));if(!b){toast('Payment receipt not found');return;}if(b.receiptText){showReceipt('Discord Payment Receipt',b.receiptText);return;}const p=paymentPayloadFromBatch(b);if(!p){toast('Payment receipt can no longer be reconstructed');return;}const text=paymentReceipt(p);b.payload=p;b.receiptText=text;save(false);showReceipt('Discord Payment Receipt',text);}"
assert old in s, 'openPaymentBatch block not found'
s=s.replace(old,new,1)

p.write_text(s)
print('patched v1.4.3 ultra compact receipt wire format')
